### ISSUE TITLE
Add compatibility to other mods

### ISSUE THREAD

**Issue by 5cript** [5cript/StrangeMatter#7]

**Comment by Xelan255** [comment]
I wrote this on your mod page as well, but since the mod page sucks in terms of notifactions I'll copy it in here too:
I play mostly with infinite ore patches, but judging from what I need to build the biggest production for: You need lead and zinc the most, along with titanium (rutile) and tungsten. As far as I can tell Bob is keeping his stuff relativly close to reality in terms of crafting processes, so I would suggest making rutile a bit more expansive, since it's rarer in general, maybe 2 matter/ore. Lead and zinc are common, as is tungsten so I would suggest to go with your default cost of 1.6matter/ore.
As for all the unmentioned ores, in my experience you don't need them in large quantaties thoughout the game, so I don't see anything wrong with going with your default value of 1.6/ore as well. Since the only things you tuned with lower costs are wood and stone I don't see any reason to tune any bob's ore under 1.6

**Comment by Xelan255** [comment]
Oh, almost forgot: There are new alient artifacts as well. I would suggest the following:
red: 2k matter/artifact
green:  2k
yellow: 1,8k
purple: 1,8k
orange: 1,6k
blue: 1,6k
I took your vanilla artifact tuning as a baseline and went up from those because of two reasons: First: the new artifacts are more rare, so should therefore be more expansive to produce. Second: You need blue +orange for the first tier of new military tech (generators, shields etc), yellow +purple for the 2nd tier and green+red for the best gear available. 
I personally am not a fan of the tuning because I think the costs are too high. One MK II matter fabricator and therefore 1GW of power to produce one single artifact every couple of seconds is not an effective ratio. Then again I'm more of a peaceful player and and tend to just blast the aliens in my way. Just my 2 Cents here. 
Oh and sorry for double posting, just wanted to make sure you read this too, and not coming back after finishing your work on the ore support and THEN seeing my edited post ;)

**Comment by 5cript** [comment]
I consider artifacts to be the "single most rare thing". I don't want to flood players with them. 
At least for me it would ruin the game.

**Comment by Xelan255** [comment]
Understandable. Then the above mentioned tunings should be fine.

**Comment by 5cript** [comment]
After over a year, this is finally a thing.
